### PR TITLE
Unnecesary call to gapi.auth.getToken()?

### PR DESCRIPTION
**Pull request by zugaldia**
According to the [docs](https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauthauthorize) the callback in gapi.auth.authorize() already receives the OAuth 2.0 token as its parameter.

### CODE REVIEW

**Comment by dhermes** [comment]
Thanks for the heads-up.

Have you signed the CLA in:
https://github.com/GoogleCloudPlatform/appengine-endpoints-tictactoe-python/blob/master/CONTRIB.md

I checked your name on our (very large) list but didn't see it. Let me know if/when you do sign it.

**SIDE NOTE**: I noticed you asking about G+ sign-in on the forum, you should check out my fork of this sample if you're curious. In particular: https://github.com/dhermes/appengine-endpoints-tictactoe-python/commit/2fcdc7f492280e14ca9c71a9c8da7f8c0c4c7cae

**Comment by zugaldia** [comment]
Hey Danny, thanks for following up. I just signed the (individual) CLA.

Interested in that fork, I'll definitely check it out. SIDE NOTE: big fan of the endpoints_proto_datastore, plan to use it in a major project and hopefully submit some patches/ideas.

**Comment by dhermes** [comment]
Thanks for signing the CLA, I confirmed your signature. Also, thanks for the kind words about Endpoints Proto Datastore. I'm all for ideas and have a few existing issues that need some good discussion.

**Comment by dhermes** [comment]
@zugaldia Sorry I let this go by. Google I/O really hosed me!

Anyhow, as of our switch to using Google+ Sign-In, this is no longer necessary.

Cheers!

**Comment by zugaldia** [comment]
No worries, keep up the good work.

**Pull request closed without merging**
